default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false

BasketCatchBrain:
    batch_size: 128
    beta: 1.0e-3
    buffer_size: 2048
    gamma: 0.99
    hidden_units: 64
    learning_rate: 3.0e-4
    max_steps: 5.0e6
    num_epoch: 5
    num_layers: 2
    time_horizon: 32
    
BallLabyrinthBrain:
    batch_size: 256
    beta: 1.0e-3
    buffer_size: 8192
    gamma: 0.99
    hidden_units: 96
    learning_rate: 3.0e-4
    max_steps: 1.0e6
    num_epoch: 5
    num_layers: 2
    time_horizon: 2048
    summary_freq: 5000